- name: GVL Galaxy - Set genomespace urls to point to GVL versions
  replace: dest="{{ galaxy_server_dir }}/{{ item }}" regexp="dm.genomespace.org" replace="{{ gvl_genomespace_server }}"
  with_items:
    - tools/genomespace/genomespace_exporter.py
    - tools/genomespace/genomespace_file_browser.py
    - tools/genomespace/genomespace_importer.py
    - tools/genomespace/genomespace_file_browser_prod.xml

- name: GVL Galaxy - Set genomespace openid config to point to GVL Genomspace server
  replace: dest="{{ galaxy_server_dir }}/{{ item }}" regexp="identity.genomespace.org" replace="{{ gvl_genomespace_server }}"
  with_items:
    - openid/genomespace.xml

- name: Create tool folder for GATK2
  file:
    path: '{{ galaxyFS_base_dir }}/tools/gatk2'
    state: 'directory'
    mode: '0755'
    owner: "{{ galaxy_user_name }}"

- name: Fetch GATK2
  get_url: url="https://swift.rc.nectar.org.au:8888/v1/AUTH_2bb45090fdb74f8c81359fbe723e4ab5/alonie/GenomeAnalysisTK-2.8.jar" dest="{{ galaxyFS_base_dir }}/tools/gatk2/GenomeAnalysisTK.jar"
  sudo: yes
  sudo_user: "{{ galaxy_user_name }}"

- name: Set GATK2 Path
  shell: executable=/bin/bash echo 'GATK2_PATH={{ galaxyFS_base_dir }}/tools/gatk2; export GATK2_PATH' > /mnt/galaxy/tools/environment_settings/GATK2_PATH/iuc/gatk2/*/env.sh
  sudo: yes
  sudo_user: "{{ galaxy_user_name }}"

# Patch up all bowtie2 executable paths so that there's a bowtie2-align executable in each (tophat2 looks for the bowtie2-align executable when running with modules on the commandline)
- name: Patchup bowtie2 executable paths so they work with tophat2 and modules
  shell: executable=/bin/bash cd {{ item }}/*/package*/*/; ln -s bowtie2 bowtie2-align
  with_fileglob:
    - "{{ galaxy_server_dir }}/tools/bowtie2/*"
  sudo: yes
  sudo_user: "{{ galaxy_user_name }}"

# Install mako to satisfy proportional venn
- name: Install mako lib to satisfy proportional venn
  pip: name=mako virtualenv={{ galaxy_tools_base_dir }}/.venv
  sudo: yes
  sudo_user: "{{ galaxy_user_name }}"
